name: build-dev-onpush

on:
  push:
    branches: [ development ]

env:
  ARTIFACTS_PATH: './src/GreenCobra.Client/bin/Release/net6.0/*/publish/'
  DOTNET_VERSION: '6.0.x'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        os: [win, linux, osx]
        arch: [arm64, x64]
        include: 
          - os: linux
            arch: x86
        
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
      
      - name: Display structure of artifacts
        run: ls -R
      
#      - name: Call composite Action build single file
#      - uses: ./.github/actions/build-dot-net-single-file
#        with: 
#          os: ${{ matrix.os }}
#          arch: ${{ matrix.arch }}
      
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: ${{ env.DOTNET_VERSION }}
#          
#      - name: Restore Dependencies
#        run: dotnet restore
#        
#      - name: Build 
#        run: |
#          dotnet build -c Release --no-restore
#          dotnet publish -c Release -r ${{ matrix.os }}-${{ matrix.arch }} --sc -p:DebugSymbols=false -p:DebugType=None
#
#      - name: Display structure of artifacts
#        run: ls -R
#        
#      - name: Upload Artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: ${{ matrix.os }}-${{ matrix.arch }}
#          path: ./src/GreenCobra.Client/bin/Release/net6.0/${{ matrix.os }}-${{ matrix.arch }}/publish/