name: build-dev-push

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish .NET
      uses: ./.github/actions/dotnet-publish.yml
      with:
        rid: win-x64