name: build-dev-onpush

on:
  push:
    branches: [ development ]

#env:
#  ARTIFACTS_PATH: './src/GreenCobra.Client/bin/Release/net6.0/*/publish/'
#  DOTNET_VERSION: '6.0.x'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        os: [win, linux, osx]
        arch: [arm64, x64]
        #include: 
        #  - os: linux
        #    arch: x86
        
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
          
      - name: Call composite Action build single file
        uses: ./.github/actions/build-dot-net-single-file
        with: 
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}