name: build-dev-onpush

on:
  push:
    branches: [ development ]

jobs:
#  build:
#    uses: ./.github/workflows/dotnet-publish.yml
#    with:
#      rid: win-x64
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Publish
        run: dotnet publish -r ${{ inputs.rid }} -c Release --sc -p:DebugSymbols=false -p:DebugType=None
      
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: "./"