name: build-dev-onpush

on:
  push:
    branches: [ development ]

jobs:
  build:
    uses: ./.github/workflows/dotnet-publish.yml
    with:
      rid: win-x64
        
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: "./"
      - name: Display structure of files
        run: ls -R