name: client-dev-publish

permissions:
  contents: write

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -p:PublishProfile=WindowsProfile -c Release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          src/GreenCobra.Client/bin/Debug/net6.0/publish/GreenCobra.Client.exe
