name: client-dev-publish

permissions:
  contents: write

on:
  push:
    branches: [ development ]
  create:
    tags:
      - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: | 
        dotnet publish -p:PublishProfile=WindowsProfile -c Release -p:DebugSymbols=false -p:DebugType=None
        dotnet publish -p:PublishProfile=LinuxProfile -c Release -p:DebugSymbols=false -p:DebugType=None
        dotnet publish -p:PublishProfile=OsxProfile -c Release -p:DebugSymbols=false -p:DebugType=None
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')        
      with:
        generate_release_notes: true
        files: |
          src/GreenCobra.Client/bin/Release/*/publish/*