name: docker-release

permissions:
  contents: write

on:
  push:
    branches: [ development ]

jobs:
  push-docker-image:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call composite Action build single file
        uses: ./.github/actions/build-dot-net-single-file
        with:
          os: linux
          arch: x64

      - name: Login to the Container registry
        uses: docker/login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-and-push-action@v2
        with:
          context: .
          push: true
          tags: green-cobra/client:latest
          #, green-cobra/client:{{ .Tag }}