name: dev-release

permissions:
  contents: write

on:
  workflow_dispatch:
        
jobs:
  push-docker-image:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call composite Action build single file
          uses: ./.github/actions/build-dot-net-single-file
          with:
            os: linux
            arch: x64
            
      - name: Login to the Container registry
        uses: docker/login@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-and-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: green-cobra/client:latest
          #, green-cobra/client:{{ .Tag }}